### ISSUE TITLE
获取账号

### ISSUE THREAD

**Issue by KevinGong2013** [DoloresTeam/dolores-ios#4]
留下自己的手机号码和昵称，会有机器人（目前还是人工来做～）帮你添加账号。
登录方式为: 手机号+默认密码(123456)

**Comment by yuzhongxingke** [comment]
173****9556  UpDay 谢谢

**Comment by KevinGong2013** [comment]
@yuzhongxingke 账号已经添加，请用自己的手机号加初始密码123456登录，请尽快修改默认密码。

**Comment by yuzhongxingke** [comment]
@KevinGong2013 
好像不能登录，点击登录不跳转

**Comment by KevinGong2013** [comment]
@yuzhongxingke  不好意思之前手机号没有复制正确，现在可以登录了。另外iOS端的错误提示有点问题，一会会修复下。

**Comment by PittChan** [comment]
136****0409 .  simon . 谢谢

**Comment by KevinGong2013** [comment]
@PittChan Done~

**Comment by taiyang799** [comment]
138****5284  snail,谢谢

**Comment by KevinGong2013** [comment]
@taiyang799 Done~

**Comment by JackieDai** [comment]
Tel:136 **** 1355  NickName:JackieDai
Tel:176 **** 2582  NickName:SmallSix

**Comment by KevinGong2013** [comment]
@JackieDai Done

**Comment by oRhino** [comment]
173****0036, Rhino,谢谢

**Comment by KevinGong2013** [comment]
@oRhino Done.

**Comment by Asensiki** [comment]
133****3885 + 123456

**Comment by KevinGong2013** [comment]
@Wiimz Done

**Comment by 54853315** [comment]
体验一下！
159****4439

**Comment by KevinGong2013** [comment]
@54853315 Done

**Comment by xiaobai-ios** [comment]
13266736250 谢谢

**Comment by black1997** [comment]
137****7173.      谢谢

**Comment by KevinGong2013** [comment]
@black1997 Done

**Comment by BOOMBOOMTom** [comment]
176****5210 Tom 谢谢啦

**Comment by KevinGong2013** [comment]
@LondonYoungWriterOfCountry Done~

**Comment by 791620110** [comment]
188****0348      123456

**Comment by KevinGong2013** [comment]
@791620110 Done.

**Comment by kilent** [comment]
177****1330 William

**Comment by KevinGong2013** [comment]
@kilent Done~

**Comment by wyk190576528** [comment]
15028135033,学习一下

**Comment by KevinGong2013** [comment]
@wyk190576528 阿里云到期了， 没有在线的试用方法了～
你可以在本地起个服务。

**Comment by dragonherd** [comment]
帳號：15344895331
密碼：123456
謝謝
